"""Claude (Claude Code CLI) session parser.

Parses individual session .jsonl files for full conversation data,
including subagent conversations stored in {session-id}/subagents/ directories.

Claude Code stores each conversation event as a separate JSONL line with
a top-level ``type`` field (``"user"`` or ``"assistant"``).  Tool use
follows the Anthropic Messages API convention: tool invocations appear
as ``tool_use`` content blocks inside assistant messages, while their
results come back as ``tool_result`` blocks inside the *next* user
message, linked by ``tool_use_id``.  This two-message pairing requires
a pre-scan to build the result map before constructing ToolCall objects.
"""

import hashlib
import re
from collections import Counter, deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, NamedTuple
from uuid import uuid4

from vibelens.ingest.diagnostics import DiagnosticsCollector
from vibelens.ingest.parsers.base import BaseParser
from vibelens.ingest.parsers.helpers import (
    ROLE_TO_SOURCE,
    build_multimodal_message,
    extract_tool_result_content,
    is_meaningful_prompt,
    iter_jsonl_safe,
    truncate_first_message,
)
from vibelens.models.enums import AgentType, ContentType, StepSource
from vibelens.models.trajectories import (
    Agent,
    Observation,
    ObservationResult,
    Step,
    ToolCall,
    Trajectory,
    TrajectoryRef,
)
from vibelens.models.trajectories.content import Base64Source, ContentPart
from vibelens.models.trajectories.metrics import Metrics
from vibelens.models.trajectories.trajectory import DEFAULT_ATIF_VERSION
from vibelens.utils import coerce_to_string, get_logger, normalize_timestamp

logger = get_logger(__name__)

# Only "user" and "assistant" carry conversation content.
# Other types (e.g. "result", "progress") are internal bookkeeping.
RELEVANT_TYPES = {"user", "assistant"}

# history.jsonl sits alongside project session files in ~/.claude/
HISTORY_INDEX_FILENAME = "history.jsonl"

# Sub-agent sessions live in {session-id}/subagents/ directories
SUBAGENTS_DIR_NAME = "subagents"

# Number of lines to probe for project path extraction
PROJECT_PATH_PROBE_LIMIT = 10

# Directories excluded from recursive session file discovery
_SKIP_DIR_NAMES = {SUBAGENTS_DIR_NAME, "parsed", "plugins"}

# Tool names that spawn sub-agent JSONL files in subagents/ directory.
# Claude Code renamed "Agent" to "Task" in later versions.
_SUBAGENT_TOOL_NAMES = {"Agent", "Task"}

# Prefix for compaction sub-agents — system-internal context compaction,
# not spawned via Agent/Task tool_use, so parent linkage never exists.
COMPACTION_AGENT_PREFIX = "acompact-"

# Tool names that invoke a skill in Claude Code. Activation only — reading
# a SKILL.md via Read/Bash/Grep doesn't count (that's just file content
# access, not skill activation).
_SKILL_TOOL_NAMES: frozenset[str] = frozenset({"Skill"})

# Pattern to extract agentId from Task/Agent tool_result content.
# Claude Code embeds "agentId: {hex_hash}" in the tool output text.
_AGENT_ID_PATTERN = re.compile(r"agentId:\s*([a-f0-9]+)")

# Pattern to find the external file path in <persisted-output> blocks.
# Claude Code saves tool results >100KB to external .txt files.
_PERSISTED_PATH_PATTERN = re.compile(r"Full output saved to: (.+?)(?:\n|$)")

# Reject paths longer than this to avoid pathological file reads
MAX_PATH_LENGTH = 1024

# XML tags injected by the system into user message content.
# Their presence means the "user" entry is actually system-generated.
_SYSTEM_XML_TAGS = frozenset(
    {
        "system-reminder",
        "local-command-caveat",
        "local-command-stdout",
        "command-message",
        "task-notification",
        "user-prompt-submit-hook",
        "command-name",
    }
)

_SYSTEM_TAG_PATTERN = re.compile(
    r"^\s*<(" + "|".join(re.escape(t) for t in _SYSTEM_XML_TAGS) + r")[\s>]"
)

# Plain-text prefixes that indicate system-injected content
_SYSTEM_PREFIXES = ("[Request interrupted", "This session is being continued")

# Claude Code echoes pasted images as a "[Image: source: <path>]" text block
# in a follow-up user turn. The previous turn already carries the image as
# a base64 block, so the echo is noise — filter it from the displayed text.
_IMAGE_SOURCE_PLACEHOLDER_RE = re.compile(r"^\s*\[Image: source: [^\]]+\]\s*$")

# Skill output injected after a Skill tool_use
_SKILL_PREFIX = "Base directory for this skill:"

# Prefixes that indicate auto-generated prompts (not typed by user directly).
# These are still semantically "user" messages but were generated by plan mode,
# context continuation, or other automated workflows.
_AUTO_PROMPT_PREFIXES = ("Implement the following plan", "Execute the following plan")


class _SessionMeta(NamedTuple):
    """Aggregated metadata from a single pass over raw JSONL content."""

    session_id: str | None
    last_session_id: str | None
    model_name: str | None
    version: str | None
    project_path: str | None
    git_branches: list[str] | None


class ClaudeParser(BaseParser):
    """Parser for Claude Code's native JSONL format.

    Handles both the history index (history.jsonl) and individual
    session files, including subagent conversations.
    """

    AGENT_TYPE = AgentType.CLAUDE
    LOCAL_DATA_DIR: Path | None = Path.home() / ".claude"
    # Claude Code names every session file with a globally-unique UUID, so we
    # use the bare stem as session_id. Keeps share/bookmark URLs stable.
    NAMESPACE_SESSION_IDS = False

    def discover_session_files(self, data_dir: Path) -> list[Path]:
        """Find Claude Code session JSONL files, excluding sub-agents and history index."""
        return [
            f
            for f in sorted(data_dir.rglob("*.jsonl"))
            if not _SKIP_DIR_NAMES.intersection(f.parts)
            and f.name != HISTORY_INDEX_FILENAME
            and not f.name.startswith("._")
        ]

    def get_session_files(self, session_file: Path) -> list[Path]:
        """Return main session file plus all sub-agent JSONL files."""
        files = [session_file]
        subagent_dir = session_file.parent / session_file.stem / SUBAGENTS_DIR_NAME
        if subagent_dir.is_dir():
            files.extend(sorted(subagent_dir.glob("agent-*.jsonl")))
        return files

    # ---- 4-stage parsing ----
    def _decode_file(self, file_path: Path, diagnostics: DiagnosticsCollector) -> str | None:
        """Stage 1: read raw JSONL content. Decoding is delayed to later stages
        because both metadata scan and step build re-walk the same JSONL."""
        try:
            return file_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            logger.warning("Cannot read Claude session %s: %s", file_path, exc)
            return None

    def _extract_metadata(
        self, raw: str, file_path: Path, diagnostics: DiagnosticsCollector
    ) -> Trajectory | None:
        """Stage 2: session_id / model / git branches / continuation ref.

        Sub-agent files (under ``<sid>/subagents/``) inherit their parent's
        in-file ``sessionId`` but need a unique trajectory id; we use the
        filename stem (e.g. ``agent-001``) so they don't collide with the main.
        """
        meta = _scan_session_metadata(raw)
        is_subagent = file_path.parent.name == SUBAGENTS_DIR_NAME
        if is_subagent:
            session_id = file_path.stem
        else:
            session_id = meta.session_id or file_path.stem or str(uuid4())
        prev_ref = TrajectoryRef(session_id=meta.last_session_id) if meta.last_session_id else None
        extra: dict[str, Any] = {}
        if meta.git_branches:
            extra["git_branches"] = meta.git_branches
        return Trajectory(
            session_id=session_id,
            agent=self.build_agent(version=meta.version, model_name=meta.model_name),
            project_path=meta.project_path,
            prev_trajectory_ref=prev_ref,
            extra=extra or None,
        )

    def _build_steps(
        self, raw: str, traj: Trajectory, file_path: Path, diagnostics: DiagnosticsCollector
    ) -> list[Step]:
        """Stage 3: build steps + in-step linkage for ``Task`` / ``Agent`` spawn pairs.

        ``_build_agent_spawn_map`` regex-extracts ``agentId: <hex>`` from each
        spawn ``tool_result`` text; the matching observation gets its
        ``subagent_trajectory_ref`` set right here, so ``_load_subagents``
        only has to locate child files.
        """
        steps = self._parse_content(raw, diagnostics=diagnostics)
        if not steps:
            if diagnostics.parsed_lines == 0 and diagnostics.total_lines > 0:
                logger.warning(
                    "No parseable entries in %s (%d lines, %d skipped)",
                    file_path,
                    diagnostics.total_lines,
                    diagnostics.skipped_lines,
                )
            return []
        spawn_map = _build_agent_spawn_map(raw, steps)
        for agent_id, spawn in spawn_map.items():
            _, tool_call_id = spawn
            _link_subagent_to_parent(steps, tool_call_id, f"agent-{agent_id}")
        return steps

    def _load_subagents(self, main: Trajectory, file_path: Path) -> list[Trajectory]:
        """Locate ``<sid>/subagents/{agent,acompact}-*.jsonl`` files and parse each.
        Per-call linkage (step_id + tool_call_id) is recovered from
        ``main.steps`` observations populated in stage 3. Compaction
        sub-agents (``acompact-*``) have no parent linkage by design.
        """
        subagent_dir = file_path.parent / file_path.stem / SUBAGENTS_DIR_NAME
        if not subagent_dir.is_dir():
            return []
        # Compaction sub-agents are named ``agent-acompact-*.jsonl`` in real
        # data (not bare ``acompact-*``), so the standard ``agent-*`` glob
        # picks them up. The compaction-prefix substring check below
        # distinguishes them from regular sub-agents.
        agent_files = sorted(subagent_dir.glob("agent-*.jsonl"))
        if not agent_files:
            return []

        # agent_session_id → (step_id, tool_call_id) recovered from in-step linkage.
        spawn_locations: dict[str, tuple[str, str | None]] = {}
        for step in main.steps:
            if step.observation is None:
                continue
            for result in step.observation.results:
                if not result.subagent_trajectory_ref:
                    continue
                for ref in result.subagent_trajectory_ref:
                    spawn_locations[ref.session_id] = (step.step_id, result.source_call_id)

        subs: list[Trajectory] = []
        for agent_file in agent_files:
            sub = self._parse_trajectory(agent_file)
            if sub is None:
                continue
            step_id, tool_call_id = spawn_locations.get(agent_file.stem, (None, None))
            sub.parent_trajectory_ref = TrajectoryRef(
                session_id=main.session_id,
                step_id=step_id,
                tool_call_id=tool_call_id,
                trajectory_path=str(file_path),
            )
            # Compaction agents flagged via filename prefix substring (real-data
            # filenames are ``agent-acompact-{hex}``, so a startswith check
            # would miss them). One trajectory-level flag, no per-step tagging:
            # the typical compaction is 2 events (summary prompt + summary
            # response) but pathological sessions (broken Stop hooks, runaway
            # loops) bloat to thousands of events — tagging every step would
            # inflate the cross-parser ``is_compaction`` count for one event.
            if COMPACTION_AGENT_PREFIX in agent_file.stem:
                sub.extra = {**(sub.extra or {}), "is_compaction": True}
            subs.append(sub)

        if subs:
            _validate_subagent_linkage(main, subs)
            main.extra = {**(main.extra or {}), "sub_agent_count": len(subs)}
        return subs

    def parse_skeleton_for_file(self, jsonl_file: Path) -> Trajectory | None:
        """Read a session file until the first meaningful user message.

        Stops as soon as a usable first message is found. Returns None
        when the file has no meaningful user message — those sessions
        are dropped from the index by the downstream validator.
        """
        first_message: str | None = None
        project_path: str | None = None
        start_ts: datetime | None = None

        for entry in iter_jsonl_safe(jsonl_file):
            if not isinstance(entry, dict):
                continue
            if project_path is None:
                cwd = entry.get("cwd")
                if isinstance(cwd, str) and cwd:
                    project_path = cwd
            if start_ts is None:
                start_ts = normalize_timestamp(entry.get("timestamp"))
            if entry.get("type") != "user":
                continue
            msg = entry.get("message")
            if not isinstance(msg, dict):
                continue
            text = _scan_user_text(msg.get("content"))
            if text and is_meaningful_prompt(text):
                first_message = truncate_first_message(text)
                break

        if not first_message:
            return None

        # File mtime is a reliable proxy for last activity: Claude Code
        # appends to the JSONL on every event, so the file modification
        # time is the timestamp of the most recent event in the session.
        try:
            mtime = datetime.fromtimestamp(jsonl_file.stat().st_mtime, tz=timezone.utc)
        except OSError:
            mtime = None

        return Trajectory(
            schema_version=DEFAULT_ATIF_VERSION,
            session_id=jsonl_file.stem,
            project_path=project_path,
            created_at=start_ts,
            updated_at=mtime or start_ts,
            first_message=first_message,
            agent=Agent(name=self.AGENT_TYPE.value),
            steps=[
                Step(
                    step_id="index-0",
                    source=StepSource.USER,
                    message=first_message,
                    timestamp=start_ts,
                )
            ],
            extra={"is_skeleton": True},
        )

    def parse_session_jsonl(self, file_path: Path) -> list[Step]:
        """Parse a session .jsonl file into main-session steps only.

        Args:
            file_path: Path to the session .jsonl file.

        Returns:
            List of Step objects for the main session (no sub-agents).
        """
        try:
            content = file_path.read_text(encoding="utf-8")
        except OSError:
            logger.debug("Cannot read file: %s", file_path)
            return []
        return self._parse_content(content)

    def _parse_content(
        self, content: str, diagnostics: DiagnosticsCollector | None = None
    ) -> list[Step]:
        """Parse JSONL content into Steps.

        Pipeline:
          1. Decode JSONL + filter to relevant types (with queue-op synthesis)
          2. Drop replay duplicates (compaction can re-emit a uuid)
          3. Pre-scan user messages for tool_result blocks → tool_use_id map
          4. Group assistant entries by message.id (streaming-chunk merge)
          5. Per group: build a Step (or None for tool-relay user messages)
          6. Record orphaned tool_use / tool_result IDs in diagnostics

        ``canonical_sid`` for ``is_copied_context`` is recovered from the
        in-file ``session_meta`` rather than passed in — sub-agent files use
        a synthetic trajectory id (filename stem) but their entries carry
        the parent's sessionId, which is the right comparator.
        """
        entries = _deduplicate_entries_by_uuid(_parse_jsonl_content(content, diagnostics))
        canonical_sid = _scan_session_metadata(content).session_id
        tool_results = _collect_tool_results(entries)
        seen_call_ids: set[str] = set()

        steps: list[Step] = []
        for group in _group_entries_by_step(entries):
            step = _step_from_group(group, tool_results, canonical_sid, seen_call_ids, diagnostics)
            if step is not None:
                steps.append(step)

        if diagnostics:
            _detect_orphans(seen_call_ids, tool_results, diagnostics)
        return steps


def _scan_session_metadata(content: str) -> _SessionMeta:
    """Extract all session-level metadata in a single JSONL pass.

    Collects sessionId, model, version, cwd (project path), and
    gitBranch from raw JSONL entries. Project path probing respects
    PROJECT_PATH_PROBE_LIMIT for consistency with the original behavior.

    Args:
        content: Raw JSONL content string.

    Returns:
        _SessionMeta with all extracted fields.
    """
    session_counter: Counter[str] = Counter()
    model_counter: Counter[str] = Counter()
    version: str | None = None
    cwd_values: list[str] = []
    branches: set[str] = set()

    for entry in iter_jsonl_safe(content):
        sid = entry.get("sessionId", "")
        if sid:
            session_counter[sid] += 1

        if version is None:
            raw_version = entry.get("version", "")
            if raw_version:
                version = str(raw_version)

        # Project path: only probe first N entries that have cwd
        if len(cwd_values) < PROJECT_PATH_PROBE_LIMIT:
            cwd = entry.get("cwd", "")
            if cwd:
                cwd_values.append(cwd)

        branch = entry.get("gitBranch", "")
        if branch:
            branches.add(branch)

        msg = entry.get("message", {})
        if isinstance(msg, dict):
            model = msg.get("model", "")
            if model and not model.startswith("<"):
                model_counter[model] += 1

    session_id = session_counter.most_common(1)[0][0] if session_counter else None
    last_session_id = None
    for sid in session_counter:
        if sid != session_id:
            last_session_id = sid
            break

    model_name = model_counter.most_common(1)[0][0] if model_counter else None
    project_path = Counter(cwd_values).most_common(1)[0][0] if cwd_values else None
    git_branches = sorted(branches) if branches else None

    return _SessionMeta(
        session_id=session_id,
        last_session_id=last_session_id,
        model_name=model_name,
        version=version,
        project_path=project_path,
        git_branches=git_branches,
    )


def _step_from_group(
    group: list[dict],
    tool_results: dict[str, dict],
    canonical_sid: str | None,
    seen_call_ids: set[str],
    diagnostics: DiagnosticsCollector | None,
) -> Step | None:
    """Convert one entry group to a Step, or None for tool-relay user messages.

    Tool-relay = a ``type: "user"`` entry whose content is only ``tool_result``
    blocks; its content is already injected into the preceding assistant step
    via the pre-scanned ``tool_results`` map, so we drop it here to avoid
    phantom user steps. Skill outputs (text user messages linked to a Skill
    tool_use via ``sourceToolUseID``) are absorbed the same way — their
    content already becomes the Skill tool call's observation.
    """
    entry = _merge_entry_group(group)
    if _is_skill_output_entry(entry):
        return None
    msg = entry.get("message", {})
    role = msg.get("role", entry.get("type", ""))
    source = ROLE_TO_SOURCE.get(role, StepSource.USER)

    message, reasoning_content, tool_calls, observation = _decompose_raw_content(
        msg.get("content", ""), tool_results
    )
    if source == StepSource.USER and not message and not tool_calls and observation is None:
        return None

    # Reclassify user-role messages that carry system / auto-prompt content.
    classify_extra: dict[str, Any] | None = None
    if source == StepSource.USER and message and isinstance(message, str):
        source, classify_extra = classify_user_message(message, entry)

    for tc in tool_calls:
        if tc.tool_call_id:
            seen_call_ids.add(tc.tool_call_id)
            if diagnostics:
                diagnostics.record_tool_call()

    # Assistant entries reuse ``message.id`` so streaming chunks collapse to one
    # step_id; user entries fall back to entry.uuid to avoid colliding when a
    # tool-relay shares an id.
    if source == StepSource.AGENT:
        step_id = msg.get("id") or entry.get("uuid", str(uuid4()))
    else:
        step_id = entry.get("uuid", str(uuid4()))

    entry_sid = entry.get("sessionId", "")
    is_copied = bool(canonical_sid and entry_sid and entry_sid != canonical_sid)

    return Step(
        step_id=step_id,
        source=source,
        message=message,
        reasoning_content=reasoning_content,
        model_name=msg.get("model") or None,
        timestamp=normalize_timestamp(entry.get("timestamp")),
        metrics=_build_step_metrics(msg.get("usage")),
        tool_calls=tool_calls,
        observation=observation,
        is_copied_context=True if is_copied else None,
        extra=_build_step_extra(entry, classify_extra=classify_extra),
    )


def _parse_jsonl_content(
    content: str, diagnostics: DiagnosticsCollector | None = None
) -> list[dict]:
    """Parse JSONL content string into relevant entry dicts.

    Filters for RELEVANT_TYPES, handles queue-operation events, and
    tracks parse quality via diagnostics.

    Queue-operation handling: when a user types while the assistant is
    still processing, Claude Code queues the message as an ``enqueue``
    event. If it's later delivered normally, a ``dequeue`` event appears
    followed by a regular ``type: "user"`` message. If instead it's
    injected as a system-reminder and removed, only ``enqueue`` +
    ``remove`` exist — no standalone user message is emitted. We create
    synthetic user entries for enqueue+remove pairs to preserve that
    user intent.

    Args:
        content: Raw JSONL content.
        diagnostics: Optional collector for tracking skipped lines.

    Returns:
        List of parsed dicts with relevant types only.
    """
    all_parsed: list[dict] = list(iter_jsonl_safe(content, diagnostics=diagnostics))

    # Pre-scan: identify enqueue timestamps that were later dequeued
    # (delivered as normal user messages). Only enqueue+remove pairs
    # need synthetic user entries.
    dequeued_timestamps = _collect_dequeued_timestamps(all_parsed)

    raw_entries: list[dict] = []
    for entry in all_parsed:
        entry_type = entry.get("type")
        if entry_type in RELEVANT_TYPES:
            raw_entries.append(entry)
            continue
        if (
            entry_type == "queue-operation"
            and entry.get("operation") == "enqueue"
            and entry.get("content")
            and entry.get("timestamp", "") not in dequeued_timestamps
        ):
            raw_entries.append(_make_enqueue_user_entry(entry))
    return raw_entries


def _deduplicate_entries_by_uuid(entries: list[dict]) -> list[dict]:
    """Drop entries whose uuid has already appeared in this stream.

    Claude Code occasionally re-emits the same JSONL line (observed with
    compaction replay, where a prior turn is re-written). Emitting
    both copies produces Step objects with duplicate step_id, which the
    Trajectory validator then rejects. Keeping only the first occurrence
    preserves ordering without losing information.
    """
    seen: set[str] = set()
    deduped: list[dict] = []
    for entry in entries:
        uuid = entry.get("uuid", "")
        if uuid and uuid in seen:
            continue
        if uuid:
            seen.add(uuid)
        deduped.append(entry)
    return deduped


def _collect_tool_results(raw_entries: list[dict]) -> dict[str, dict]:
    """Build a mapping of tool_use_id -> result from user messages.

    Uses a plain dict (unbounded) so that long sessions with many tool
    calls do not lose early results to eviction. Also captures the
    event-level ``toolUseResult`` field (structured metadata like
    exit_code, stdout, stderr) for downstream extraction.

    Skill activations: Claude returns the SKILL.md content as a separate
    user-role text message linked back to the originating tool_use via
    ``sourceToolUseID`` (rather than a ``tool_result`` content block).
    Treat those as the tool result for the Skill tool call so the regular
    tool-call+observation rendering pipeline handles them — no synthetic
    user step needed.
    """
    tool_results: dict[str, dict] = {}
    for entry in raw_entries:
        if entry.get("type") != "user":
            continue
        msg = entry.get("message", {})
        content = msg.get("content", "")
        if not isinstance(content, list):
            continue
        # Event-level toolUseResult carries structured execution metadata
        tool_use_result = entry.get("toolUseResult")

        # Skill outputs always overwrite any prior tool_result for the same
        # tool_use_id. Claude emits a short "Launching skill: <name>" ack as
        # a normal tool_result block AND the actual SKILL.md content as a
        # separate text entry; the latter is what the user wants to see.
        source_tool_id = entry.get("sourceToolUseID")
        if source_tool_id:
            text_parts = [
                b.get("text", "")
                for b in content
                if isinstance(b, dict) and b.get("type") == "text"
            ]
            joined = "".join(t for t in text_parts if t)
            if joined.lstrip().startswith(_SKILL_PREFIX):
                tool_results[source_tool_id] = {"output": joined, "is_error": False}

        for block in content:
            if block.get("type") == "tool_result":
                tool_use_id = block.get("tool_use_id", "")
                if tool_use_id:
                    result_content = block.get("content", "")
                    is_error = block.get("is_error", False)
                    # Preserve raw content (may contain image blocks)
                    has_images = isinstance(result_content, list) and any(
                        isinstance(b, dict) and b.get("type") == "image" for b in result_content
                    )
                    output: str | list = (
                        result_content if has_images else coerce_to_string(result_content)
                    )
                    result_entry: dict = {"output": output, "is_error": bool(is_error)}
                    if tool_use_result and isinstance(tool_use_result, dict):
                        result_entry["tool_use_result"] = tool_use_result
                    tool_results[tool_use_id] = result_entry
    return tool_results


def _group_entries_by_step(entries: list[dict]) -> list[list[dict]]:
    """Group entries by logical step using message.id for assistant entries.

    Assistant entries sharing a message.id are collected into a single group
    even when separated by user tool-relay entries (which become their own
    singleton groups). Groups are ordered by first appearance.

    Args:
        entries: Flat list of parsed JSONL entries.

    Returns:
        List of entry groups; each group becomes one Step.
    """
    groups: list[list[dict]] = []
    msg_id_to_group: dict[str, list[dict]] = {}

    for entry in entries:
        entry_type = entry.get("type")
        msg_id = entry.get("message", {}).get("id", "")

        if entry_type == "assistant" and msg_id:
            if msg_id in msg_id_to_group:
                msg_id_to_group[msg_id].append(entry)
            else:
                group: list[dict] = [entry]
                groups.append(group)
                msg_id_to_group[msg_id] = group
        else:
            groups.append([entry])

    return groups


def _detect_orphans(
    tool_use_ids: set[str], tool_results: dict[str, dict], diagnostics: DiagnosticsCollector
) -> None:
    """Record total tool-result count plus any tool_use / tool_result orphans."""
    result_ids = tool_results.keys()
    for _ in result_ids:
        diagnostics.record_tool_result()
    for tc_id in tool_use_ids - result_ids:
        diagnostics.record_orphaned_call(tc_id)
    for result_id in result_ids - tool_use_ids:
        diagnostics.record_orphaned_result(result_id)


def _build_agent_spawn_map(
    raw_content: str, parent_steps: list[Step]
) -> dict[str, tuple[str, str]]:
    """Build agentId → (step_id, tool_call_id) map from raw JSONL.

    Scans raw JSONL directly (not parsed steps) to avoid missing
    entries evicted from the bounded tool result cache. For each
    Task/Agent tool_use, finds the corresponding tool_result and
    extracts the 'agentId: {hash}' embedded in the output text.

    Args:
        raw_content: Raw JSONL content of the main session.
        parent_steps: Parsed steps for resolving tool_call_id → step_id.

    Returns:
        Dict mapping agentId to (step_id, tool_call_id).
    """
    # Single pass: collect spawn tool_use_ids from assistant messages
    # and tool_result candidates from user messages simultaneously
    spawn_tc_ids: set[str] = set()
    result_candidates: list[tuple[str, str]] = []  # (tool_use_id, text_content)

    for entry in iter_jsonl_safe(raw_content):
        entry_type = entry.get("type")
        msg = entry.get("message", {})
        if not isinstance(msg, dict):
            continue

        if entry_type == "assistant":
            for block in msg.get("content", []):
                if not isinstance(block, dict):
                    continue
                if block.get("type") == "tool_use" and block.get("name") in _SUBAGENT_TOOL_NAMES:
                    tc_id = block.get("id", "")
                    if tc_id:
                        spawn_tc_ids.add(tc_id)

        elif entry_type == "user":
            for block in msg.get("content", []):
                if not isinstance(block, dict) or block.get("type") != "tool_result":
                    continue
                tc_id = block.get("tool_use_id", "")
                if not tc_id:
                    continue
                result_content = block.get("content", "")
                if isinstance(result_content, list):
                    result_content = " ".join(
                        b.get("text", "") for b in result_content if isinstance(b, dict)
                    )
                result_content = str(result_content)
                if "<persisted-output>" in result_content:
                    result_content = _read_persisted_agent_id(result_content)
                result_candidates.append((tc_id, result_content))

    if not spawn_tc_ids:
        return {}

    # Filter candidates against spawn_tc_ids and extract agentId
    agent_to_tc: dict[str, str] = {}
    for tc_id, text in result_candidates:
        if tc_id not in spawn_tc_ids:
            continue
        match = _AGENT_ID_PATTERN.search(text)
        if match:
            agent_to_tc[match.group(1)] = tc_id

    # Resolve tool_call_id → step_id via parsed steps
    tc_to_step_id: dict[str, str] = {}
    for step in parent_steps:
        for tc in step.tool_calls:
            if tc.tool_call_id in spawn_tc_ids:
                tc_to_step_id[tc.tool_call_id] = step.step_id

    return {
        agent_id: (tc_to_step_id.get(tc_id, ""), tc_id) for agent_id, tc_id in agent_to_tc.items()
    }


def _link_subagent_to_parent(
    parent_steps: list[Step], spawn_tool_call_id: str, sub_agent_id: str
) -> None:
    """Add a subagent_trajectory_ref to the parent step's observation.

    Args:
        parent_steps: Steps from the parent session.
        spawn_tool_call_id: Tool call ID that spawned the sub-agent.
        sub_agent_id: Session ID of the sub-agent trajectory.
    """
    for step in parent_steps:
        if not step.observation:
            continue
        for result in step.observation.results:
            if result.source_call_id == spawn_tool_call_id:
                ref = TrajectoryRef(session_id=sub_agent_id)
                if result.subagent_trajectory_ref is None:
                    result.subagent_trajectory_ref = [ref]
                else:
                    result.subagent_trajectory_ref.append(ref)
                return


def _validate_subagent_linkage(
    main_trajectory: Trajectory, sub_trajectories: list[Trajectory]
) -> None:
    """Warn about broken subagent references between parent and children.

    Checks two invariants:
    - Every subagent_trajectory_ref.session_id in the parent points to
      an existing sub-trajectory.
    - Every sub-trajectory is referenced by at least one parent step.

    Uses logger.warning (not errors) since subagent files may be missing
    or the session may have been interrupted before completion.

    Args:
        main_trajectory: The parent session trajectory.
        sub_trajectories: List of parsed sub-agent trajectories.
    """
    sub_ids = {t.session_id for t in sub_trajectories}

    # Collect all subagent refs from parent observation results
    parent_refs: set[str] = set()
    for step in main_trajectory.steps:
        if not step.observation:
            continue
        for result in step.observation.results:
            if result.subagent_trajectory_ref:
                for ref in result.subagent_trajectory_ref:
                    parent_refs.add(ref.session_id)

    # Parent refs pointing to missing sub-trajectories
    dangling_refs = parent_refs - sub_ids
    if dangling_refs:
        logger.warning(
            "Session %s: parent references missing sub-trajectories: %s",
            main_trajectory.session_id,
            dangling_refs,
        )

    # Sub-trajectories not referenced by any parent step — expected for
    # compaction agents (system-internal) and persisted-output edge cases.
    unreferenced = sub_ids - parent_refs
    if unreferenced:
        # Identify compaction agents by extra flag (preferred) or session_id prefix (fallback)
        sub_by_id = {t.session_id: t for t in sub_trajectories}
        compaction = {
            sid
            for sid in unreferenced
            if (sub_by_id[sid].extra or {}).get("is_compaction") or COMPACTION_AGENT_PREFIX in sid
        }
        regular = unreferenced - compaction
        if compaction:
            logger.debug(
                "Session %s: %d compaction sub-agent(s) (system-internal, no parent linkage)",
                main_trajectory.session_id,
                len(compaction),
            )
        if regular:
            logger.debug(
                "Session %s: sub-trajectories not referenced by parent: %s",
                main_trajectory.session_id,
                regular,
            )


def _is_skill_output_entry(entry: dict[str, Any]) -> bool:
    """Whether this user-role entry is the SKILL.md output of a Skill tool call.

    Identified by ``sourceToolUseID`` plus a text body starting with the
    skill-output prefix. Such entries are consumed by ``_collect_tool_results``
    as the Skill tool call's observation, so the entry itself should not
    materialise as a synthetic user step.
    """
    if entry.get("type") != "user":
        return False
    if not entry.get("sourceToolUseID"):
        return False
    msg = entry.get("message", {})
    if not isinstance(msg, dict):
        return False
    content = msg.get("content", "")
    if isinstance(content, str):
        return content.lstrip().startswith(_SKILL_PREFIX)
    if isinstance(content, list):
        for block in content:
            if (
                isinstance(block, dict)
                and block.get("type") == "text"
                and str(block.get("text", "")).lstrip().startswith(_SKILL_PREFIX)
            ):
                return True
    return False


def classify_user_message(
    text: str, entry: dict[str, Any]
) -> tuple[StepSource, dict[str, Any] | None]:
    """Classify a user-role message as real user, system, or auto-generated.

    Claude Code injects system content (XML tags, continuation notices) and
    plan mode output into user-type entries. This function detects those
    patterns and returns the correct source classification with metadata.

    Skill outputs are filtered earlier (see :func:`_is_skill_output_entry`)
    and never reach this function — they become the Skill tool call's
    observation instead of a separate user step.

    Args:
        text: The text content of a user-type message.
        entry: Raw JSONL entry dict (currently unused; kept for parity).

    Returns:
        Tuple of (source, extra_metadata). Extra is None for system/plain user
        or ``{"is_auto_prompt": True}`` for auto-generated prompts (e.g. plan mode).
    """
    if not text:
        return StepSource.USER, None

    stripped = text.lstrip()

    if _SYSTEM_TAG_PATTERN.match(stripped):
        return StepSource.SYSTEM, None

    for prefix in _SYSTEM_PREFIXES:
        if stripped.startswith(prefix):
            return StepSource.SYSTEM, None

    # Auto-generated prompts from plan mode or automated workflows
    for prefix in _AUTO_PROMPT_PREFIXES:
        if stripped.startswith(prefix):
            return StepSource.USER, {"is_auto_prompt": True}
    return StepSource.USER, None


def _decompose_raw_content(
    raw_content: str | list, tool_results: dict[str, dict] | None = None
) -> tuple[str, str | None, list[ToolCall], Observation | None]:
    """Decompose Anthropic Messages API content into separated Step fields.

    Converts the polymorphic content block array from Claude Code API
    responses into separated ATIF Step fields: message (text),
    reasoning_content (thinking), tool_calls, and observation.

    When tool_results is provided, injects matching tool results from
    the pre-scan map to produce proper Observation objects.

    Args:
        raw_content: Raw content from JSONL entry (str or list of dicts).
        tool_results: Optional pre-scanned tool_use_id -> result mapping.

    Returns:
        Tuple of (message, reasoning_content, tool_calls, observation).
    """
    if isinstance(raw_content, str):
        stripped = raw_content.strip()
        return (stripped, None, [], None) if stripped else ("", None, [], None)

    if not isinstance(raw_content, list):
        return ("", None, [], None)

    text_parts: list[str] = []
    image_parts: list[ContentPart] = []
    thinking_parts: list[str] = []
    tool_calls: list[ToolCall] = []
    obs_results: list[ObservationResult] = []
    tool_results = tool_results or {}

    for block in raw_content:
        if not isinstance(block, dict):
            continue
        block_type = block.get("type", "text")

        if block_type == "text":
            text = block.get("text", "")
            if text and not _IMAGE_SOURCE_PLACEHOLDER_RE.match(text):
                text_parts.append(text)

        elif block_type == "image":
            source = block.get("source", {})
            if isinstance(source, dict) and source.get("type") == "base64":
                image_parts.append(
                    ContentPart(
                        type=ContentType.IMAGE,
                        source=Base64Source(
                            media_type=source.get("media_type", "image/png"),
                            base64=source.get("data", ""),
                        ),
                    )
                )

        elif block_type == "thinking":
            thinking = block.get("thinking", "")
            if thinking:
                thinking_parts.append(thinking)

        elif block_type == "tool_use":
            tool_call_id = block.get("id", "")
            tool_name = block.get("name", "")
            tool_calls.append(
                ToolCall(
                    tool_call_id=tool_call_id,
                    function_name=tool_name,
                    arguments=block.get("input"),
                    is_skill=True if tool_name in _SKILL_TOOL_NAMES else None,
                )
            )
            # Inject pre-scanned tool result if available
            result = tool_results.get(tool_call_id) if tool_call_id else None
            if result:
                obs_results.append(
                    ObservationResult(
                        source_call_id=tool_call_id,
                        content=extract_tool_result_content(result.get("output")),
                        is_error=bool(result.get("is_error")),
                        extra=_extract_tool_result_metadata(result),
                    )
                )

        elif block_type == "tool_result":
            # When pre-scan results are available, tool_result blocks are
            # already captured via the tool_use branch above. Skip direct
            # processing to prevent duplicate ObservationResults.
            if tool_results:
                continue
            obs_results.append(
                ObservationResult(
                    source_call_id=block.get("tool_use_id", ""),
                    content=extract_tool_result_content(block.get("content")),
                    is_error=bool(block.get("is_error")),
                )
            )

    joined_text = "\n\n".join(text_parts).strip() if text_parts else ""
    message = build_multimodal_message(joined_text, image_parts)
    reasoning_content = "\n\n".join(thinking_parts).strip() if thinking_parts else None
    observation = Observation(results=obs_results) if obs_results else None

    return message, reasoning_content, tool_calls, observation


def _merge_entry_group(group: list[dict]) -> dict:
    """Merge a group of streaming chunks into a single pseudo-entry.

    Concatenates message.content lists from all entries in the group.
    Uses the first entry's uuid, timestamp, and metadata as the base.

    Args:
        group: One or more JSONL entries sharing the same message.id.

    Returns:
        Single merged entry dict.
    """
    if len(group) == 1:
        return group[0]

    merged = dict(group[0])
    merged_msg = dict(merged.get("message", {}))

    # Concatenate content lists from all chunks
    all_content: list = []
    for entry in group:
        chunk_content = entry.get("message", {}).get("content", "")
        if isinstance(chunk_content, list):
            all_content.extend(chunk_content)
        elif chunk_content:
            all_content.append({"type": "text", "text": str(chunk_content)})

    merged_msg["content"] = all_content
    merged["message"] = merged_msg
    return merged


def _build_step_metrics(usage_data: dict | None) -> Metrics | None:
    """Build a :class:`Metrics` from an Anthropic-style ``usage`` dict, or None."""
    if not usage_data:
        return None
    return Metrics.from_tokens(
        input_tokens=usage_data.get("input_tokens") or 0,
        output_tokens=usage_data.get("output_tokens") or 0,
        cache_read_tokens=usage_data.get("cache_read_input_tokens") or 0,
        cache_write_tokens=usage_data.get("cache_creation_input_tokens") or 0,
    )


def _build_step_extra(
    entry: dict, classify_extra: dict[str, Any] | None = None
) -> dict[str, Any] | None:
    """Build step-level extra dict from Claude Code entry fields.

    Extracts format-specific metadata (is_sidechain, stop_reason, stop_sequence,
    cwd, request_id, service_tier, user_type) and merges in any classifier
    extras (currently just ``is_auto_prompt``) returned by
    :func:`classify_user_message`.
    """
    extra: dict[str, Any] = {}
    msg = entry.get("message", {})
    if not isinstance(msg, dict):
        msg = {}

    if entry.get("_queue_operation"):
        extra["is_queued_prompt"] = True

    if entry.get("isSidechain", False):
        extra["is_sidechain"] = True

    if msg.get("stop_reason") is not None:
        extra["stop_reason"] = msg["stop_reason"]

    if msg.get("stop_sequence") is not None:
        extra["stop_sequence"] = msg["stop_sequence"]

    if entry.get("cwd"):
        extra["cwd"] = entry["cwd"]

    if msg.get("requestId"):
        extra["request_id"] = msg["requestId"]

    if msg.get("service_tier"):
        extra["service_tier"] = msg["service_tier"]

    if entry.get("userType") and entry["userType"] != "external":
        extra["user_type"] = entry["userType"]

    if classify_extra:
        extra.update(classify_extra)

    return extra or None


def _collect_dequeued_timestamps(all_parsed: list[dict]) -> set[str]:
    """Return enqueue timestamps that were paired with a later dequeue.

    Dequeue events don't reference the original enqueue — they only
    record their own (delivery) timestamp, which lands a few ms after
    the enqueue. Pair them FIFO by occurrence order so the matching
    survives that drift.

    Dequeued messages are delivered as normal ``type: "user"`` entries,
    so creating a synthetic user entry would duplicate them.

    Args:
        all_parsed: All parsed JSONL entries (unfiltered).

    Returns:
        Set of enqueue timestamp strings that were paired with a dequeue.
    """
    pending_enqueue_ts: deque[str] = deque()
    delivered: set[str] = set()
    for entry in all_parsed:
        if entry.get("type") != "queue-operation":
            continue
        op = entry.get("operation")
        if op == "enqueue":
            ts = entry.get("timestamp", "")
            if ts:
                pending_enqueue_ts.append(ts)
        elif op == "dequeue" and pending_enqueue_ts:
            delivered.add(pending_enqueue_ts.popleft())
    return delivered


def _make_enqueue_user_entry(entry: dict) -> dict:
    """Transform a queue-operation enqueue event into a synthetic user entry.

    When a user types a message while the assistant is still processing,
    Claude Code queues it as an enqueue event. If the message is later
    removed (not dequeued), no standalone user message exists — the
    enqueue is the only record of the user's input.

    Args:
        entry: Raw queue-operation JSONL entry with operation="enqueue".

    Returns:
        Synthetic user entry compatible with _parse_content() processing.
    """
    ts = entry.get("timestamp", "")
    session_id = entry.get("sessionId", "")
    content_repr = coerce_to_string(entry.get("content", ""))
    # Hash session+timestamp+content so re-parsing the same JSONL produces
    # the same uuid (stable step_ids across runs). md5 is a fingerprint, not
    # a security claim. Distinct enqueues at the same ts still get distinct
    # ids; true duplicates collapse via _deduplicate_entries_by_uuid.
    digest = hashlib.md5(
        f"{session_id}|{ts}|{content_repr}".encode(), usedforsecurity=False
    ).hexdigest()[:8]
    unique_id = f"enqueue-{ts}-{digest}" if ts else f"enqueue-{digest}"
    return {
        "type": "user",
        "uuid": unique_id,
        "sessionId": entry.get("sessionId", ""),
        "timestamp": entry.get("timestamp"),
        "message": {"role": "user", "content": entry["content"]},
        "_queue_operation": "enqueue",
    }


def _scan_user_text(content) -> str:
    """Extract human-typed text from a raw user-message ``content`` field.

    Handles both shapes Claude Code emits — string content and the
    Anthropic content-block list — joining text blocks while skipping
    image-source echoes and non-text blocks (images, tool_result). Used
    by the lightweight index scan; full parsing goes through
    :func:`_decompose_raw_content`.
    """
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    parts: list[str] = []
    for block in content:
        if not isinstance(block, dict) or block.get("type") != "text":
            continue
        text = block.get("text", "")
        if text and not _IMAGE_SOURCE_PLACEHOLDER_RE.match(text):
            parts.append(text)
    return "\n\n".join(parts)


def _read_persisted_agent_id(content: str) -> str:
    """Read a persisted tool output file to extract agentId.

    When tool_result content contains a <persisted-output> pointer,
    read the referenced file and return its tail (agentId is near the end).
    Returns original content if the file cannot be read.
    """
    match = _PERSISTED_PATH_PATTERN.search(content)
    if not match:
        return content
    raw_path = match.group(1).strip()
    # Guard against regex capturing content blobs instead of real file paths
    if len(raw_path) > MAX_PATH_LENGTH or "\n" in raw_path:
        return content
    path = Path(raw_path)
    try:
        if not path.is_file():
            return content
        text = path.read_text(encoding="utf-8", errors="replace")
        # agentId is near the end of Agent tool output
        TAIL_SIZE = 2000
        return text[-TAIL_SIZE:] if len(text) > TAIL_SIZE else text
    except OSError:
        return content


def _extract_tool_result_metadata(result: dict) -> dict[str, Any] | None:
    """Extract structured execution metadata from a cached tool result.

    When the tool result cache contains a ``tool_use_result`` dict (captured
    from the event-level ``toolUseResult`` field), extracts salient fields:
    exit_code, stdout, stderr, and interrupted.

    Args:
        result: A single entry from the tool_results cache dict.

    Returns:
        Metadata dict, or None if no structured metadata is available.
    """
    tur = result.get("tool_use_result")
    if not isinstance(tur, dict):
        return None

    meta: dict[str, Any] = {}
    exit_code = tur.get("exitCode")
    if exit_code is None:
        exit_code = tur.get("exit_code")
    if exit_code is not None:
        meta["exit_code"] = exit_code

    stdout = tur.get("stdout")
    if isinstance(stdout, str):
        meta["stdout"] = stdout

    stderr = tur.get("stderr")
    if isinstance(stderr, str):
        meta["stderr"] = stderr

    if tur.get("interrupted"):
        meta["interrupted"] = True

    return meta or None
